name: THE-DEVIL-BOLTE

on: push

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v2

      - name: Find and Replace

        uses: jacobtomlinson/gha-find-replace@master

        with:

          find: "MAFIA-USERBOT"

          replace: "OPGHOULS-USERBOT"

      - name: Create Pull Request

        uses: stefanzweifel/git-auto-commit-action@v4

        with:

          commit_message: 'Replaced new name'

          commit_options: '--no-verify'

          repository: .

          commit_user_name: THE-DEVIL-BOLTE

          commit_user_email: devilpreet93@gmail.com
